### PR TITLE
Fix submit tags BUG

### PR DESCRIPTION
**Pull request by Mattraks**
I’m not sure what your "tags" function means,
I think it’s whether to sync tags.
When "tags" is not enabled, some tags will be synchronized

### CODE REVIEW

**Review by turbaszek — COMMENTED** [review]
@Mattraks can you explain what exactly is being fixed here?

**Comment by Mattraks** [comment]
> @Mattraks can you explain what exactly is being fixed here?

I’m not sure what your "tags" function means,
I think it’s whether to sync tags.
When "tags" is not enabled, some tags will be synchronized

**Comment by TobKed** [comment]
@Mattraks thank you very much for your contribution.
I see your point, now `--follow-tags` paramter is always implicitly used, despite of `tags` option.

I was thinking about changing the way of passing parameters to `push` by deprecating inputs like `force` and `tags` and adding more general argument like `push_options` where any of [git push options](https://git-scm.com/docs/git-push#_options) could be passed. WDYT @Mattraks @turbaszek ?

**Comment by TobKed** [comment]
@Mattraks thanks you for contribution.
Based on your changes I made fix (https://github.com/TobKed/github-forks-sync-action/commit/f1df98d5e1ee99be18bf6b551049970d3f00e2cf) since I couldn't do it directly in this PR.

**Pull request closed without merging**
